(function(global){
  "use strict";
  const VERSION="0.6.6-brain-liecio-loop";
  const loopChannels=new Set(["heart","latencyBall","healthRing","warnings","alarms","training"]);
  const state={ctx:null,enabled:true,activeChannel:"",volume:.85,bpm:68,rhythm:"normal",lagMs:0,timer:null,lastAt:0,players:{},asset:{brain:"assets/sound/brain-liecio-mysterious-drone-pad-loop.mp3"},unlocked:false,deviceStatus:null,lastTest:null,primer:null,lagOsc:null,lagOsc2:null,lagLfo:null,lagLfoGain:null,lagGain:null,lagFilter:null,lagRunning:false};
  const defaults={latencyBall:true,healthRing:false,heart:false,brain:false,warnings:false,alarms:false,training:false};
  function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)||0))}
  function AC(){return global.AudioContext||global.webkitAudioContext}
  function startPrimer(){if(!state.ctx||state.primer)return;try{const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type="sine";o.frequency.setValueAtTime(18,state.ctx.currentTime);g.gain.setValueAtTime(.0008,state.ctx.currentTime);o.connect(g).connect(state.ctx.destination);o.start();state.primer={o,g}}catch(_){}}
  function stopPrimer(){if(!state.primer)return;try{state.primer.o.stop();state.primer.o.disconnect();state.primer.g.disconnect()}catch(_){}state.primer=null}
  async function unlock(){try{const C=AC();if(!C)return false;state.ctx=state.ctx||new C({latencyHint:"interactive"});if(state.ctx.state==="suspended")await state.ctx.resume();state.unlocked=state.ctx.state==="running";if(state.unlocked)startPrimer();return state.unlocked}catch(_){state.unlocked=false;return false}}
  function now(){return state.ctx?state.ctx.currentTime:0}
  function audioVolume(scale=1){return clamp(state.volume*scale,.02,1)}
  function env(at,dur,vol,attack=.006,release=.025){const g=state.ctx.createGain();g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(Math.max(.0001,vol),at+attack);g.gain.exponentialRampToValueAtTime(.0001,at+dur+release);return g}
  function osc(type,freq,at,dur,vol,slide){const o=state.ctx.createOscillator(),g=env(at,dur,vol);o.type=type;o.frequency.setValueAtTime(Math.max(20,freq),at);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,slide),at+dur);o.connect(g).connect(state.ctx.destination);o.start(at);o.stop(at+dur+.06)}
  function noise(at,dur,vol,filterFreq=2200){const c=state.ctx,b=c.createBuffer(1,Math.max(1,Math.floor(c.sampleRate*dur)),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2.2);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=env(at,dur,vol,.003,.025);f.type="bandpass";f.frequency.setValueAtTime(filterFreq,at);f.Q.setValueAtTime(6,at);s.buffer=b;s.connect(f).connect(g).connect(c.destination);s.start(at);s.stop(at+dur+.04)}
  function stopLagDrone(){if(!state.lagRunning&&!state.lagOsc)return;const at=now();try{if(state.lagGain)state.lagGain.gain.setTargetAtTime(.0001,at,.04);[state.lagOsc,state.lagOsc2,state.lagLfo].forEach(o=>{try{o&&o.stop(at+.18)}catch(_){}})}catch(_){}state.lagOsc=null;state.lagOsc2=null;state.lagLfo=null;state.lagLfoGain=null;state.lagGain=null;state.lagFilter=null;state.lagRunning=false}
  function stopTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}state.lastAt=0;stopLagDrone()}
  function stopBrain(){const a=state.players.brain;if(a){try{a.pause();a.currentTime=0}catch(_){}}}
  function stopAll(){stopTimer();stopBrain();stopPrimer();state.activeChannel=""}
  function isActive(ch){return state.enabled&&state.activeChannel===ch}
  async function playBrain(){if(!state.enabled||state.activeChannel!=="brain")return false;try{const src=state.asset.brain;let a=state.players.brain;if(!a||a._src!==src){a=new Audio(src);a.loop=true;a.preload="auto";a._src=src;state.players.brain=a}a.volume=audioVolume(.70);await a.play();return true}catch(_){return false}}
  async function beepHeart(alarm=false){if(!isActive("heart")||!await unlock())return false;const at=now(),v=audioVolume(alarm?1:.95);osc("sine",alarm?1500:1250,at,alarm?.075:.060,v,alarm?850:1250);osc("triangle",alarm?2800:2200,at+.004,alarm?.045:.035,v*.30,alarm?1500:2200);return true}
  function lagFrequency(){const lag=clamp(state.lagMs,0,1500),level=lag/1500;return 72+level*520}
  function updateLagDrone(){if(!state.ctx||!isActive("latencyBall"))return false;const at=now(),lag=clamp(state.lagMs,0,1500),level=lag/1500,freq=lagFrequency(),vol=audioVolume(.16+level*.42),filter=520+level*2600,lfo=0.12+level*1.15;if(!state.lagOsc){const c=state.ctx;state.lagOsc=c.createOscillator();state.lagOsc2=c.createOscillator();state.lagLfo=c.createOscillator();state.lagLfoGain=c.createGain();state.lagFilter=c.createBiquadFilter();state.lagGain=c.createGain();state.lagOsc.type="sawtooth";state.lagOsc2.type="sine";state.lagLfo.type="sine";state.lagFilter.type="lowpass";state.lagFilter.Q.setValueAtTime(2.2,at);state.lagGain.gain.setValueAtTime(.0001,at);state.lagLfo.connect(state.lagLfoGain);state.lagLfoGain.connect(state.lagOsc.frequency);state.lagOsc.connect(state.lagFilter);state.lagOsc2.connect(state.lagFilter);state.lagFilter.connect(state.lagGain).connect(c.destination);state.lagOsc.start();state.lagOsc2.start();state.lagLfo.start();state.lagRunning=true}state.lagOsc.frequency.setTargetAtTime(freq,at,.08);state.lagOsc2.frequency.setTargetAtTime(freq*.5,at,.10);state.lagLfo.frequency.setTargetAtTime(lfo,at,.10);state.lagLfoGain.gain.setTargetAtTime(2+level*24,at,.10);state.lagFilter.frequency.setTargetAtTime(filter,at,.12);state.lagGain.gain.setTargetAtTime(Math.max(.0001,vol),at,.10);return true}
  async function lagPulse(){if(!isActive("latencyBall")||!await unlock())return false;return updateLagDrone()}
  async function ringPulse(){if(!isActive("healthRing")||!await unlock())return false;const at=now(),v=audioVolume(.55);osc("triangle",430,at,.13,v,520);osc("sine",860,at+.04,.08,v*.25,760);return true}
  async function warnPulse(){if(!isActive("warnings")||!await unlock())return false;const at=now(),v=audioVolume(.85);osc("sine",660,at,.14,v,590);osc("sine",520,at+.18,.15,v*.8,480);return true}
  async function alarmPulse(){if(!isActive("alarms")||!await unlock())return false;const at=now(),v=audioVolume(.95);for(let i=0;i<3;i++){const t=at+i*.16;osc("sawtooth",820,t,.10,v,1220);osc("square",390,t+.01,.08,v*.45,250);noise(t,.065,v*.28,3300)}return true}
  async function trainingPulse(){if(!isActive("training")||!await unlock())return false;const at=now(),v=audioVolume(.65);osc("triangle",440,at,.10,v,520);osc("triangle",660,at+.12,.12,v,720);return true}
  function heartDelay(){if(state.rhythm==="vf")return 90+Math.random()*150;if(state.rhythm==="signal")return 360+Math.random()*360;if(state.rhythm==="asystole"||state.rhythm==="off")return 1800;return Math.round(60000/clamp(state.bpm||68,30,180))}
  function loopDelay(){if(state.activeChannel==="heart")return heartDelay();if(state.activeChannel==="latencyBall")return 90;if(state.activeChannel==="healthRing")return 900;if(state.activeChannel==="warnings")return 4200;if(state.activeChannel==="alarms")return 2600;if(state.activeChannel==="training")return 3000;return 1000}
  function fireCurrent(){const ch=state.activeChannel;if(ch==="heart")return beepHeart(state.rhythm==="vf"||state.rhythm==="signal"||state.rhythm==="asystole");if(ch==="latencyBall")return lagPulse();if(ch==="healthRing")return ringPulse();if(ch==="warnings")return warnPulse();if(ch==="alarms")return alarmPulse();if(ch==="training")return trainingPulse();return false}
  function startTimer(){stopTimer();if(!loopChannels.has(state.activeChannel))return;state.lastAt=0;state.timer=setInterval(()=>{if(!state.enabled||!loopChannels.has(state.activeChannel))return;const ms=Date.now(),delay=loopDelay();if(!state.lastAt||ms-state.lastAt>=delay){state.lastAt=ms;fireCurrent()}},60);state.lastAt=Date.now();fireCurrent()}
  async function activateChannel(channel){await unlock();const next=channel||"";if(next===state.activeChannel&&((next==="brain"&&state.players.brain&&!state.players.brain.paused)||(loopChannels.has(next)&&state.timer))){return snapshot()}stopTimer();if(next!=="brain")stopBrain();state.activeChannel=next;if(!next)return snapshot();if(next==="brain"){await playBrain()}else if(loopChannels.has(next)){startTimer()}else{await test(next)}return snapshot()}
  function setActiveChannel(channel){state.activeChannel=channel||"";if(!state.activeChannel){stopAll()}}
  function configure(options={}){if("enabled" in options){state.enabled=options.enabled!==false;if(!state.enabled)stopAll()}if("volume" in options){state.volume=clamp(options.volume,0,1);if(state.players.brain)state.players.brain.volume=audioVolume(.70);if(state.lagGain)state.lagGain.gain.setTargetAtTime(audioVolume(.16+clamp(state.lagMs,0,1500)/1500*.42),now(),.08)}if("bpm" in options)state.bpm=clamp(options.bpm,0,220);if("rhythm" in options)state.rhythm=options.rhythm||"normal";if("lagMs" in options){state.lagMs=clamp(options.lagMs,0,5000);if(state.activeChannel==="latencyBall")updateLagDrone()}if(options.assets&&options.assets.brain)state.asset.brain=options.assets.brain;if("activeChannel" in options){const next=options.activeChannel||"";if(!next)stopAll();else if(next!==state.activeChannel){stopTimer();if(next!=="brain")stopBrain();state.activeChannel=next}}return snapshot()}
  async function checkDevice(){const webAudio=!!AC(),unlocked=await unlock();let outputs=null,inputs=null;try{if(global.navigator?.mediaDevices?.enumerateDevices){const devices=await global.navigator.mediaDevices.enumerateDevices();outputs=devices.filter(d=>d.kind==="audiooutput").length;inputs=devices.filter(d=>d.kind==="audioinput").length}}catch(_){}const message=!webAudio?"Browser unterstuetzt WebAudio nicht.":!unlocked?"AudioContext konnte nicht gestartet werden.":outputs===0&&inputs===0?"Browser meldet kein Audiogeraet.":"Audio bereit.";state.deviceStatus={webAudio,unlocked,outputs,inputs,message,checkedAt:Date.now(),ctxState:state.ctx?.state||"none",sampleRate:state.ctx?.sampleRate||0};return state.deviceStatus}
  async function directTest(){await unlock();const at=now()+.01;osc("sine",880,at,.20,1,660);osc("square",440,at+.24,.16,.6,330);noise(at+.48,.10,.45,2400);state.lastTest={webAudio:state.unlocked,ctxState:state.ctx?.state||"none",message:"Direkter WebAudio-Test gestartet.",checkedAt:Date.now()};return state.lastTest}
  function test(channel){const prev=state.activeChannel;state.activeChannel=channel;let r;if(channel==="heart")r=beepHeart(false);else if(channel==="brain")r=playBrain();else if(channel==="latencyBall")r=lagPulse();else if(channel==="healthRing")r=ringPulse();else if(channel==="warnings")r=warnPulse();else if(channel==="alarms")r=alarmPulse();else if(channel==="training")r=trainingPulse();else r=false;state.activeChannel=prev;return r}
  function snapshot(){return {version:VERSION,enabled:state.enabled,activeChannel:state.activeChannel,volume:state.volume,unlocked:state.unlocked,deviceStatus:state.deviceStatus,lastTest:state.lastTest,loopChannel:state.timer?state.activeChannel:(state.activeChannel==="brain"?"brain":null),loopRunning:!!state.timer||(state.activeChannel==="brain"&&!!state.players.brain&&!state.players.brain.paused),bpm:state.bpm,rhythm:state.rhythm,lagMs:state.lagMs,assets:{...state.asset},channels:{...defaults}}}
  global.AudioCore={version:VERSION,unlock,checkDevice,directTest,configure,activateChannel,setEnabled:v=>configure({enabled:v}),setVolume:v=>configure({volume:v}),setActiveChannel,channelEnabled:isActive,click:lagPulse,tone:ringPulse,ekg:beepHeart,brain:playBrain,alarm:alarmPulse,warning:warnPulse,test,snapshot};
})(window);






